#!/bin/bash

curl https://raw.githubusercontent.com/21stio/aliases/master/aliases > ~/.aliases

if ! grep -q "source ~/.aliases" ~/.bashrc; then
	echo "source ~/.aliases" >> ~/.bashrc
fi

source ~/.aliases
